name: Build and Release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create and release (e.g. 1.0.0)"
        required: true
        type: string
      project:
        description: "Project to build (e.g. SubtitleRenamerWpf.csproj)"
        required: false
        type: string
        default: "SubtitleRenamerWpf.csproj"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ${{ github.event.inputs.project }}

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishTrimmed=false -o publish

      - name: Archive published app
        run: Compress-Archive -Path publish\* -DestinationPath SubtitleRenamerWpf.zip

      - name: Push tag (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Set release tag
        id: set_tag
        shell: bash
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Create Release
        id: create_release
        uses: dimi7rof/create-release@v3
        with:
          name: Release ${{ steps.set_tag.outputs.tag }}
          version: ${{ steps.set_tag.outputs.tag }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: "SubtitleRenamerWpf.zip"
